---

- name: copy artifact file
  copy:
    src: artifact.tar.gz
    dest: ~/artifact.tar.gz
    backup: yes

- name: extract artifact file
  shell: | 
    tar -zxvf artifact.tar.gz

- name: npm install 
  shell: |
    npm install

# - name: Stop node
#   shell: |
#     pm2 stop default

- name: Restart node
  shell: |
    pm2 start npm -- start